import Link from "next/link";
import { Icon } from "./icons";

type Island = { id?: string; name?: string; description?: string; metrics?: { plays?: number; uniquePlayers?: number; peakCCU?: number } };
async function getIslands(): Promise<Island[]> { try { const res=await fetch("https://api.fortnite.com/ecosystem/v1/islands",{next:{revalidate:300}}); if(!res.ok)return[]; const data=await res.json(); return Array.isArray(data)?data.slice(0,8):data?.islands?.slice(0,8)??[]; } catch{return[]} }
function number(value?:number){return typeof value==="number"?new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:1}).format(value):"—"}

export default async function Home(){const islands=await getIslands();return <main className="shell"><nav className="nav"><Link className="brand" href="/">SHADOW<span>PLAY</span></Link><div className="links"><Link href="/">Home</Link><Link href="/games">Games</Link><Link href="/watch">Play</Link><Link href="#discover">Discover</Link><Link href="#stats">Stats</Link></div><Link className="btn primary" href="/watch"><Icon name="play" size={16}/> Play Fortnite</Link></nav>
<section className="hero"><div><div className="eyebrow"><i className="dot"/> Fortnite flagship · Multi-game hub</div><h1>PLAY.<br/><span className="gradient">LIVE. NOW.</span></h1><p>Fortnite is the heart of ShadowPlay. Launch the real browser-play experience through official cloud gaming, then explore Apex Legends, Call of Duty, Black Ops 7, Free Fire, COD Mobile and PlayStation Remote Play.</p><div className="actions"><Link className="btn primary" href="/watch"><Icon name="play" size={16}/> Play Fortnite</Link><Link className="btn secondary" href="/games">Explore all games <Icon name="arrow-right" size={16}/></Link></div></div><div className="hero-card"><div className="live-head"><strong>FORTNITE CLOUD PLAY</strong><span className="live"><Icon name="check" size={14}/> READY</span></div><div className="screen"><div className="play"><Icon name="play" size={28}/></div></div><p style={{color:"#9299aa",fontSize:12,marginBottom:0}}>Launch the official Xbox Cloud Gaming session from ShadowPlay.</p></div></section>
<section className="section"><div className="section-title"><div><h2>Fortnite first. More games underneath.</h2><p>One gaming hub, with the correct official launch path for each platform.</p></div><Link className="btn secondary" href="/games">View game library <Icon name="arrow-right" size={16}/></Link></div><div className="stream-grid"><Link className="stream flagship" href="/watch"><div className="stream-top"><span><Icon name="cloud" size={22}/></span><span className="tag">FLAGSHIP</span></div><h3>Fortnite</h3><p>Real-time cloud gameplay through Xbox Cloud Gaming.</p></Link><Link className="stream" href="/games"><div className="stream-top"><span><Icon name="gamepad" size={22}/></span><span className="tag">CLOUD + CONSOLE</span></div><h3>More console games</h3><p>Black Ops 7, Call of Duty and supported PlayStation remote play paths.</p></Link><Link className="stream" href="/games"><div className="stream-top"><span><Icon name="globe" size={22}/></span><span className="tag">MOBILE</span></div><h3>Mobile games</h3><p>Apex Legends, COD Mobile and Free Fire through their official platforms.</p></Link></div></section>
<section className="section" id="discover"><div className="section-title"><div><h2>Fortnite Discover</h2><p>Island performance data from Epic's public Fortnite Data API.</p></div><Link className="btn secondary" href="#stats">View metrics <Icon name="arrow-right" size={16}/></Link></div><div className="grid">{islands.length?islands.map((island,i)=><article className="card" key={island.id??i}><div className="card-icon"><Icon name="gamepad" size={24}/></div><h3>{island.name??`Fortnite Island ${i+1}`}</h3><p>{island.description??"Public Fortnite island"}</p><div className="stat">{number(island.metrics?.peakCCU)} <span style={{fontSize:11,color:"#9299aa",fontWeight:600}}>peak CCU</span></div></article>):["Battle Royale","Zero Build","Reload","Creative"].map(x=><article className="card" key={x}><div className="card-icon"><Icon name="zap" size={24}/></div><h3>{x}</h3><p>Discoverable Fortnite experiences and their public engagement metrics.</p></article>)}</div></section>
<section className="section" id="stats"><div className="section-title"><div><h2>Real Fortnite data</h2><p>Epic's API exposes aggregated island performance metrics without authentication.</p></div></div><div className="grid"><article className="card"><div className="card-icon"><Icon name="chart" size={24}/></div><h3>Peak CCU</h3><p>Peak concurrent player count for public discoverable islands.</p></article><article className="card"><div className="card-icon"><Icon name="users" size={24}/></div><h3>Unique Players</h3><p>Distinct players represented by aggregated island metrics.</p></article><article className="card"><div className="card-icon"><Icon name="target" size={24}/></div><h3>Plays</h3><p>Total game sessions recorded for an island.</p></article><article className="card"><div className="card-icon"><Icon name="star" size={24}/></div><h3>Favorites</h3><p>How often players have favorited an island.</p></article></div></section>
<footer className="footer"><span>© 2026 ShadowPlay</span><span>Fortnite is a trademark of Epic Games, Inc.</span></footer></main>}
