import Link from "next/link";
import { games } from "../games";
import { Icon } from "../icons";

export default function GamesPage() {
  const featured = games[0];
  return <main className="shell">
    <nav className="nav"><Link className="brand" href="/">SHADOW<span>PLAY</span></Link><div className="links"><Link href="/">Home</Link><Link className="active-link" href="/games">Games</Link><Link href="/#discover">Discover</Link><Link href="/#stats">Stats</Link></div><Link className="btn primary" href="/watch">Play Fortnite</Link></nav>
    <section className="streams-hero"><div><div className="eyebrow"><i className="dot"/> Multi-game cloud hub</div><h1>Fortnite first.<br/><span className="gradient">More games too.</span></h1><p>Fortnite remains the flagship experience. ShadowPlay also gives you clear launch paths for supported cloud, console and mobile games without pretending to host games that require their official platforms.</p></div><div className="live-summary"><Icon name="gamepad" size={28}/><div><strong>{games.length} games</strong><small>Cloud, console and mobile launch paths</small></div></div></section>
    <section className="section game-feature"><div className="hero-card"><div className="live-head"><strong>FEATURED · FORTNITE</strong><span className="live"><Icon name="check" size={14}/> READY</span></div><div className="feature-copy"><div><span className="tag">XBOX CLOUD GAMING</span><h2>{featured.name}</h2><p>{featured.description}</p><div className="actions"><a className="btn primary" href={featured.playUrl}><Icon name="play" size={16}/> Play Fortnite</a><Link className="btn secondary" href="/account"><Icon name="users" size={16}/> Microsoft account help</Link></div></div></div></div></section>
    <section className="section"><div className="section-title"><div><h2>Game library</h2><p>Choose a game and ShadowPlay will send you to the correct official gameplay service.</p></div></div><div className="grid game-grid">{games.map(game=><article className={"card game-card "+(game.status==="featured"?"featured-game":"")} key={game.slug}><div className="game-icon"><Icon name={game.status==="cloud"||game.status==="featured"?"cloud":game.status==="official"?"gamepad":"globe"} size={26}/></div><span className="tag">{game.platform}</span><h3>{game.name}</h3><p>{game.description}</p><small>{game.note}</small><a className="btn secondary game-button" href={game.playUrl}>{game.status==="featured"?"Play now":"Open official service"}<Icon name="arrow-right" size={15}/></a></article>)}</div></section>
    <section className="section"><div className="notice"><strong>How streaming works</strong><br/>For cloud-playable titles, ShadowPlay opens the official cloud session so the real game video and controls come from the provider. Xbox supports browser cloud gaming on supported devices and lists Fortnite as playable with a free Microsoft account in supported regions. Other games can require Game Pass, a purchase, a mobile app, a console or a separate official service. Availability changes by region, device and game.</div></section>
    <footer className="footer"><span>© 2026 ShadowPlay</span><span>Official services only · No game files hosted</span></footer>
  </main>;
}
